// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGoCrmUser = "go_crm_user"

// GoCrmUser mapped from table <go_crm_user>
type GoCrmUser struct {
	ID int32 `gorm:"column:id" json:"id"`
}

// TableName GoCrmUser's table name
func (*GoCrmUser) TableName() string {
	return TableNameGoCrmUser
}
