server:
  port: 8082
  mode: dev
mysql:
  host: mysql_container #127.0.0.1
  port: 3306
  username: root
  password: root1234
  dbname: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
logger:
  log_level: debug
  file_log_name: "./storages/logs/dev.001.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true
redis:
  host: 127.0.0.1
  port: 6381
  password:
  database: 0
  